### ISSUE TITLE
Requirements before migration

### ISSUE THREAD

**Issue by tbkurtz** [AlmaLinux/almalinux-deploy#105]
It's not clear to me in the documentation what needs to be met before running the script.

A couple questions specifically-
1. What is the minimal supported EL release you can migrate from (does it need to be 8.5)
       ---- Edit: disregard, I see the script does in fact refuse to run if version is not 8.5
2. After migration, is a reboot required?  I assume yes to reload the new kernel - but this is not specified. 
3. Some guides out there suggest running a full dnf update and rebooting before running the migrate script - official guidance on this?

Thanks!

**Comment by krendahl-godaddy** [comment]
my 2 cents:

2) I don't think there is any technical requirement but i do it as best practice since the system just went through a full distro-sync. I would rather reboot and find out there was an issue immediately rather than later (fyi i haven't had any failures/issues as of yet). Since i've been scheduling my migrations at the same time as my CentOS 8.5 update i'm already out of rotation so another reboot isn't a big deal. I have also seen a colleague have weird grub behavior in the past if he did multiple kernel updates before rebooting (albiet cent7).

3) I have been doing a full update and reboot (if necessary) prior to running the migration script. Again not entirely sure if required since its going to do a distro-sync to whatever is in the almalinux repo's but like you i saw this recommended as well.

**Comment by tbkurtz** [comment]
Thanks, TuxCare echoed the same response.  

I think this guidance should be in the readme here.

**Comment by andrewlukoshko** [comment]
README is updated with new steps.
