### ISSUE TITLE
Need to run sudo dnf update

### ISSUE THREAD

**Issue by tonydiep** [AlmaLinux/almalinux-deploy#110]
Need to run

sudo dnf update

for after step 5

Otherwise, branding doesn't fully change and step 6 fails

**Comment by nedevl** [comment]
@tonydiep 

Hi Tony. 
It might be because of the BaseOS broken repository.

Try to edit the following files:
/etc/yum.repos.d/CentOS-Base.repo
/etc/yum.repos.d/CentOS-AppStream.repo

Change **enabled=1** to **enabled=0**
If **enabled=1** is not present just add **enabled=0**

Then try
`#yum update -y`

Most probably you sorted this out since Dec 31,2021 , but I run into the same issue and this was the way to sort the problem.
