### ISSUE TITLE
Upgrades from CentOS < 8.5 fail based on the current documentation/instructions

### ISSUE THREAD

**Issue by jonathanspw** [AlmaLinux/almalinux-deploy#115]
On step 1, the `dnf upgrade -y` will fail since CentOS 8 mirrorlists are now offline and if the user isn't already on 8.5 then `almalinux-deploy.sh` will subsequently fail.  I'm not sure if older versions of 8.5 (but not the latest) will trigger the "Please upgrade your OS" error from `almalinux-deploy.sh` but presumably not.

We can address this by updating docs to either point users to vault.centos.org to get updated, or perhaps at our own hosted copy of 8.5.2111.

**Comment by connifer** [comment]
I hit this wall right now.  I'm at 8.4.2105.  I moved to the vault repos and did a dnf update.  It said there was nothing to update.  So I can't transition to Alma unless I go to  8.5 but I can't get to 8.5 because RedHat appears to not have put it in vault.

Any ideas?  

`[root@vc8ws01 ~]# cat /etc/centos-release
CentOS Linux release 8.4.2105
[root@vc8ws01 ~]# bash almalinux-deploy.sh 
Check root privileges                                                 OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK
Please upgrade your OS from 8.4 to                                    ERROR
    at least 8.5 and try again`

**Comment by jonathanspw** [comment]
Try https://github.com/jonathanspw/almalinux-deploy/blob/centos_8_mirrorlist_dead/almalinux-deploy.sh with the `-f` flag which will handle plugging in functional repos for you until we get the PR merged.

**Comment by connifer** [comment]
I tried but it bombed (see below).  That said, I looked in the script and found the lines for the mirrors.  I ran the the seds (word?).  They updated my repo defs, yum clean all, and I was off to the races.  I'm now at 8.5.2111.  Thanks for your help!

[root@xxxxxxxx ~]# curl -O https://github.com/jonathanspw/almalinux-deploy/blob/centos_8_mirrorlist_dead/almalinux-deploy.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  504k    0  504k    0     0  4203k      0 --:--:-- --:--:-- --:--:-- 4203k
[root@xxxxxxxx ~]# bash ./almalinux-deploy.sh -f
./almalinux-deploy.sh: line 7: syntax error near unexpected token `newline'
./almalinux-deploy.sh: line 7: `<!DOCTYPE html>'
[root@xxxxxxxx ~]# bash ./almalinux-deploy.sh
./almalinux-deploy.sh: line 7: syntax error near unexpected token `newline'
./almalinux-deploy.sh: line 7: `<!DOCTYPE html>'

**Comment by connifer** [comment]
One more note.  I'm doing the migration on a network with an authenticated proxy.  For various reasons I have to manually authenticate.  When I ran the script I wasn't aware my auth had expired.  I opened a desktop to launch a browser and the desktop was missing and things looked weird (technical term).  I suspect what happened is the script already deleted/moved some stuff before it got to where it needed to download.  There was enough of my desktop that I could still luanch a browser and auth so it should be fine.  I realize this may be an edge case.  That said, you may want to consider testing for internet before it starts making changes.

Thanks again for your help.


[root@xxxxxxxx ~]# bash almalinux-deploy.sh
Check root privileges                                                 OK
Check centos-8.x86_64 is supported                                    OK
Download RPM-GPG-KEY-AlmaLinux                                        OK
Import RPM-GPG-KEY-AlmaLinux to RPM DB                                OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK
Your OS is supported                                                  OK
warning: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo saved as /etc/yum.repos.d/CentOS-Linux-PowerTools.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Linux-Plus.repo saved as /etc/yum.repos.d/CentOS-Linux-Plus.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Linux-HighAvailability.repo saved as /etc/yum.repos.d/CentOS-Linux-HighAvailability.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Linux-FastTrack.repo saved as /etc/yum.repos.d/CentOS-Linux-FastTrack.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Linux-Extras.repo saved as /etc/yum.repos.d/CentOS-Linux-Extras.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Linux-Devel.repo saved as /etc/yum.repos.d/CentOS-Linux-Devel.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Linux-ContinuousRelease.repo saved as /etc/yum.repos.d/CentOS-Linux-ContinuousRelease.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Linux-BaseOS.repo saved as /etc/yum.repos.d/CentOS-Linux-BaseOS.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Linux-AppStream.repo saved as /etc/yum.repos.d/CentOS-Linux-AppStream.repo.rpmsave
Remove OS specific rpm packages                                       OK
Verifying...                          ########################################
Preparing...                          ########################################
Updating / installing...
almalinux-release-8.5-3.el8           ########################################
Install almalinux-release package                                     OK
Remove centos-backgrounds centos-logos centos-indexhtml packages      OK
Install almalinux-backgrounds almalinux-logos almalinux-indexhtml packagesERROR
    AlmaLinux 8 - BaseOS                            3.4 MB/s | 5.8 MB     00:01
    AlmaLinux 8 - AppStream                         3.4 MB/s | 8.9 MB     00:02
    AlmaLinux 8 - Extras                            1.9 kB/s | 3.0 kB     00:01
    Errors during downloading metadata for repository 'extras':
    - Status code: 407 for http://almalinux.mirrors.itworxx.de/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://repo.almalinux.org/almalinux/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://mirror.23m.com/almalinux/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://mirror.hs-esslingen.de/Mirrors/almalinux/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://ftp.uni-bayreuth.de/linux/almalinux/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://de.mirrors.clouvider.net/almalinux/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://almalinux.repo.slimhost.com.ua/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://mirror.netzwerge.de/almalinux/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://ftp.gwdg.de/pub/linux/almalinux/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    - Status code: 407 for http://almalinux.li/8/extras/x86_64/os/repodata/repomd.xml (IP: 10.17.180.65)
    Error: Failed to download metadata for repo 'extras': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Install almalinux-backgrounds almalinux-logos almalinux-indexhtml packagesOK
Backup of alternatives is done                                        OK
Error: Failed to download metadata for repo 'extras': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by Jaspix** [comment]
Has anyone managed to fix this problem?

**Comment by lcohen999** [comment]
I was able to do it from 8.2 like this:

#1.  

sudo sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
sudo sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*

#2.  dnf distro-sync

That will bring it up to CentOS 8.5  Then run the Alma Script as normal.  

I rebooted between upgrading to 8.5 and runinng the Alma script.

I just did two servers like that tonight

**Comment by jonathanspw** [comment]
Just check out https://github.com/jonathanspw/almalinux-deploy/blob/centos_8_mirrorlist_dead/almalinux-deploy.sh with `-f`

**Comment by jonathanspw** [comment]
This is now resolved in the `master` branch.

**Comment by iovcho** [comment]
Hello. I have other issue, because I use this tutorial https://github.com/AlmaLinux/almalinux-deploy/issues/120 , and I am not run 
dnf distro-sync command.
I have this error now

[root@Stage-Deploy-One ~]# ./almalinux-deploy.sh
Check root privileges                                                 OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK
Error: Failed to download metadata for repo 'AppStream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
[root@Stage-Deploy-One ~]#

If I run with parameter -f 
[root@Stage-Deploy-One ~]# ./almalinux-deploy.sh -f
sed: can't read /etc/yum.repos.d/CentOS-Linux-BaseOS.repo: No such file or directory

If run dnf list updates
[root@Stage-Deploy-One ~]# dnf list updates
CentOS-8 - AppStream                                                                                                                                                                                          20 kB/s | 4.0 kB     00:00
Errors during downloading metadata for repository 'AppStream':
  - Status code: 503 for http://vault.centos.org/almalinux/8/AppStream/x86_64/os/repodata/repomd.xml (IP: 34.253.151.233)
Error: Failed to download metadata for repo 'AppStream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried


[root@Stage-Deploy-One ~]# cat /etc/redhat-release
AlmaLinux release 8.5 (Arctic Sphynx)
[root@Stage-Deploy-One ~]#

Somebody can help me ? Thanks!
