### ISSUE TITLE
Migrating from centos 8 to AlmaLinux 8.7 offline

### ISSUE THREAD

**Issue by MarkAntonyGit** [AlmaLinux/almalinux-deploy#158]
### Discussed in https://github.com/AlmaLinux/almalinux-deploy/discussions/157

<div type='discussions-op-text'>

<sup>Originally posted by **MarkAntonyGit** December  1, 2022</sup>
Hi folks,

Can you please suggest which all functions I need to edit in the script so that I can use a local repository for this migration script? Also please suggest which all repos I need to create locally for the migration to happen without internet. Thanks in advance!</div>

**Comment by cozzyd** [comment]
I looked into this since I am interested in doing something like this as well with a remote deployment when I visit this summer. I'm no expert, but to me  it looks like there are at least 2 things that need to happen: 

- change the centos 8 vault urls to something local
- Use a modified version of the almalinux-release rpm (https://git.almalinux.org/rpms/almalinux-release that overrides the repo lists

**Comment by cozzyd** [comment]
It looks like actually you can set up ALMA_RELEASE_URL and ALMA_PUBKEY_URL environmental variables to something before running the script, which can be a local mirror. So all you need is a local mirror and an almalinux-release rpm with modified repo files, I think, but I haven't tried it yet!

**Comment by MarkAntonyGit** [comment]
Thank you for your reply. I have already created a seperate script with
local repo. It's working fine now. Thanks again.
