### ISSUE TITLE
From Oracle Linux 8 to Alma Linux 8 : kernel-uek not removed

### ISSUE THREAD

**Issue by aaaaadrien** [AlmaLinux/almalinux-deploy#26]
The UEK kernel not removed by the script when migrating from Oracle to AlmaLinux.
The version of kernel-uek is more recent (5.4) than Alma Linux kernel (4.18).

Possibility to have issues with modules because the system boot on an old Oracle Kernel

**Comment by andrewlukoshko** [comment]
Hello.
We're not yet sure we want to remove kernel-uek automatically as we want to keep fallback kernel in case of stock kernel 4.18 won't boot for some reason (drivers etc.).
And we don't expect modules issues because modules for every kernel located in separate directory.
User may remove kernel-uek after migration by himself if everything is fine.

**Comment by taidos** [comment]
Is better remove afterwards then in the migration cycle. Just doing yum -y remove kernel-uek and is done

**Comment by andrewlukoshko** [comment]
@taidos is right.
It's better to remove kernel after migration manually than brake something during migration automatically.
Closing.
