### ISSUE TITLE
How to roll back from AlmaLinux 8 to CentOS 8?

### ISSUE THREAD

**Issue by ShikiSuen** [AlmaLinux/almalinux-deploy#73]
I am using AAPanel but found that its self-compiled components might have compatibility issues with AlmaLinux.
Does anyone have instructions on how to roll my system back from AlmaLinux to CentOS 8?

**Comment by ShikiSuen** [comment]
I gave up all hope for this. Reinstalling RHEL from scratch now.
Won't trust these non-official distros anymore. Sigh.

**Comment by philrandal** [comment]
Perhaps you can tell us what the issues you had were?

What error messages did you get?

**Comment by ShikiSuen** [comment]
I already lost all my hope with EL distros. They are still using ancient kernels.
My VPS provider doesn't support mounting user-provided ISOs... only CentOS and Fedora are available RPM-based distros.

There's also a bad nature of AAPanel that it never utilizes the system dnf / apt installation.
It recompiles everything from scratch despite your choice of fast-install. (I use PHP8 + MySQL8.)
They have actually more active support with Ubuntu & Debian, despite their announcements of focusing CentOS support.
Still, the compilation time is discouraging. I hope there will be another easy-to-use panel which rely on dnf / apt first.

**Comment by ShikiSuen** [comment]
(For this GitHub issue thread I just hope that AlmaLinux can have a script allowing users to redo the conversion.)

**Comment by Toommi** [comment]
> Make a backup of the system. We didn't test all possible scenarios so there is a risk that something goes wrong. In such a situation you will have a restore point.

**Comment by rklrkl** [comment]
"Ancient kernels" aren't an issue for EL distros - Red Hat backport fixes from later kernels, plus you can use the kernel-ml packages from ELRepo if you want the latest stable kernel built with RHEL standard kernel options ( http://elrepo.org/tiki/kernel-ml ), though I really wouldn't recommend that for a production server unless the standard "ancient" kernel doesn't actually work for you.

As for reverting the CentOS -> AlmaLinux conversion, I wrote a script that clones the "/" partition to a second identically-sized "/otheros" partition (adjusting /otheros/etc/fstab to "swap over" / and /otheros mount devices if it's booted into /otheros) - my script then runs grub2-mkconfig to pick up the copied partition and - voila - I have two copies of the OS I can boot from. Saved my bacon when alma-deploy.sh failed half-way through because I had a dnf config issue (I'm raising an issue for that). I booted into /otheros, ran the copying script to back up again over the half-installed partition and then ran alma-deploy.sh again after I fixed the dnf config issue.

**Comment by WannaBeGeekster** [comment]
ispconfig is a free open source panel that supports RPM and APT distributions.  Highly recommend it.

**Comment by ShikiSuen** [comment]
@WannaBeGeekster Thanks for your recommendation.
AAPanel always recompile what it installs, costing huge amount of time.
I wonder how ISPConfig behaves.

**Comment by andrewlukoshko** [comment]
CentOS 8 is EOL so no plans to support rollback.
